version: "3.8"
services:
  database_server:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      - SA_PASSWORD=Bam1schijf
      - ACCEPT_EULA=Y
      - DB_HOST=database_server 
    ports:
      - target: 1433
        published: 1434
        protocol: tcp
        mode: host
  web_server:
    build:
      context: ./
      dockerfile: Dockerfile-webserver
    restart: always
    env_file:
      - variables.env
    depends_on:
      - database_server
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./applicatie:/applicatie:rw
      - ./webserver-setup:/setup:rw
